### ISSUE TITLE
Setting up the blocklet development environment

### ISSUE THREAD

**Issue by keyding** [keyding/blocklet-profile#1]
### Todos

- [x] Starting a `Blocklet Server` Instance
- [x] Initialize the application using the `Create Blocklet` tool
- [x] Update dependencies and add typescript

### References

[Blocket Developer Docs](https://www.arcblock.io/docs/blocklet-developer/zh/welcome)
[Blocklet CLI](https://www.arcblock.io/docs/blocklet-developer/zh/install-blocklet-cli)
[Create Blocklet](https://www.arcblock.io/docs/createblocklet/zh/welcome2)
