### ISSUE TITLE
Add Supabase Database

### ISSUE THREAD

**Issue by keyding** [keyding/blocklet-profile#9]
## Todos

- [x] Create new project
- [x] Add `@supabase/supabase-js`
- [x] Test connect database
- [x] Store profile data
